### ISSUE TITLE
Production AOT build failed

### ISSUE THREAD

**Issue by Blarne** [infinitycube/gravatar#1]
Execution of **ng build --prod --aot** (**_npm run-script build-prod_**) for Angular 4 failed:

ERROR in Unexpected value 'Gravatar in c:/myapp/node_modules/@infinitycube/gravatar/src/gravatar.js' declared by the module 'AppModule in c:/myapp/src/app/app.module.ts'. Please add a @Pipe/@Directive/@Component annotation.

Without --aot (dev mode) application works.

node v6.11.0
npm  v3.10.10

**Comment by gopumon** [comment]
A new version of package has been published. It has been fixed in version 1.1.2. 
@Blarne Please test at your end let me know if you're still facing the same issue.
