### ISSUE TITLE
Unexpected value 'GravatarModule' when running `ng build`.

### ISSUE THREAD

**Issue by d-koppenhagen** [infinitycube/gravatar#6]
Hi, I tried to run `ng build -prod` using the Angular-CLI. It seems that there is still a problem using the GravatarModule.
I got the following error message:

```
ERROR in : Unexpected value 'GravatarModule in <PATH>/node_modules/@infinitycube/gravatar/bundles/src/gravatar.module.js' imported by the module 'AppCommonModule in <PATH>/app-common.module.ts'. Please add a @NgModule annotation.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! <MYREPO>@<MYVERSION> build: `ng build -prod`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the <MYREPO>@<MYVERSION> build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     <PATH>/.npm/_logs/2017-12-19T17_33_32_373Z-debug.log
```

using the module in dev mode running `ng serve` works properly.

The problem occurs with Version 1.3.0 (I also tried to use directly the installing it from d9a83bf) but without any success.

NPM Version: 5.5.1
NodeJS Version: 7.2.1
Angular-Version: 5.1.1
Angular-CLI Version: 1.6.1
@infinitycube/gravatar version: 1.3.0 / git@github.com:infinitycube/gravatar.git#ca5578372fb1e224fe588fced8a4bd1006bfbdd1

**Comment by JaxonWright** [comment]
I am getting the same thing

**Comment by carlos-mora** [comment]
I've run into the same issue with the latest release. ¿Is there a way to overcome this problem?

**Comment by eusthace** [comment]
Ouch, same issue since 20 Dec 2017?

Yes, the problem is still there. Any solution?

**Comment by john-sec** [comment]
You can use [ngx-gravatar](https://github.com/t-ho/ngx-gravatar) for an alternative.

**Comment by gopumon** [comment]
Old build system scrapped due to various bugs. Now `@infinitycube/gravatar@2.0.3` supports Angular 6 or later. Hope this resolve the issue.
