### ISSUE TITLE
gravatar.service.d.ts definition/declaration prevents using default gravatar fallback

### ISSUE THREAD

**Issue by jakehockey10** [infinitycube/gravatar#7]
Hello,

I'm running into an issue where if I use the `url` method of the `GravatarService` outside of a template (in typescript), I'm unable to utilize the `DefaultGravatarFallback` constant.  The implementation uses this when one does not provide the fallback in the directive, but my typescript won't transpile when I don't provide a fallback explicitly.  Is this intentional?

**Comment by jakehockey10** [comment]
Would the solution be to make the definition file look like this:

``` typescript
export declare class GravatarService {
    /**
     * Returns the url for a user's gravatar image.
     * 
     * @param {string} email email associated with gravatar account
     * @param {number} size size of gravatar image returned
     * @param {string} fallback fallback in case something goes wrong
     * @returns {string}
     * @memberof GravatarService
     */
    url(email: string, size: number, fallback?: string): string;
    /*                                       ^               */
    /*                                added '?' for fallback */
}
```

**Comment by gopumon** [comment]
Old build system scrapped due to various bugs. Now `@infinitycube/gravatar@2.0.3` supports Angular 6 or later. Fall back issue is fixed in this version.
