### ISSUE TITLE
Importing GravatarModule into AppModule as suggested in README causes ERROR

### ISSUE THREAD

**Issue by jakehockey10** [infinitycube/gravatar#8]
I'm having trouble doing a production build with this library.  So I read the README and it suggests that I import the `GravatarModule` into my `AppModule` `imports` array.  When I do this, I get an error that `GravatarModule` defined in `/node_modules/@infinitycube/gravatar/src/gravatar.module.d.ts` doesn't have the necessary `@NgModule` annotation to be an importable module.

``` bash
ERROR in : Unexpected value 'GravatarModule in path/to/app/node_modules/@infinitycube/gravatar/src/gravatar.module.d.ts' imported by the module
'AppModule in path/to/app/src/app/app.module.ts'. Please add a @NgModule annotation.
```

**Comment by kisonay** [comment]
I'm experiencing the same thing.

**Comment by michaelz** [comment]
Same here. However, it works fine on simple build (and with `ng serve`), for me it fails when I try to use the `-prod` flag on build.

I found this : https://github.com/angular/angular/issues/15763

EDIT: Updating NPM to v8.9.4 did not work, still the same issue.

**Comment by michaelz** [comment]
I finally implemented Gravatar in my PHP backend... and used a simple <img> tag like so: 
`<img [src]="user.gravatar" alt="user avatar" />` which is also very simple. Only thing is that it's less obvious on how to change the size and default image. I used the big image and adapted the css depending on the use case (should also be more retina friendly).

More info here on how to generate the hash : https://en.gravatar.com/site/implement/hash/
The final link should look like this: `https://www.gravatar.com/avatar/<hash>.jpg?d=mm` where mm is the default image.

**Comment by mtshikomba** [comment]
Same issue here.

**Comment by Segfaultd** [comment]
Same issue here

**Comment by ussamoo** [comment]
Same issue here

**Comment by john-sec** [comment]
I have the same issue. It looks like no one maintains this repo.

**Comment by gopumon** [comment]
Old build system scrapped due to various bugs. Now `@infinitycube/gravatar@2.0.3` supports Angular 6 or later. We are working on a branch to support Angular 4 and 5.  Hope this resolve the issue.
