### ISSUE TITLE
.git should be removed from this npm package

### ISSUE THREAD

**Issue by ajmorenodelarosa** [infinitycube/gravatar#9]
After installing this package I get this message when I try to install any new package from npm

Error: */node_modules/@infinitycube/gravatar: Appears to be a git repo or submodule.

The package needs to be updated to remove the .git directory from the package. As a temporary fix just go into the directory and use rm -rf .git this will stop NPM complaining.

**Comment by adchsm** [comment]
I'm also experiencing this issue.

**Comment by kumotaicho** [comment]
Same here. The first time I run npm update, it works but if if I just run the same command again, then I get the error.

Waiting for a fix, I just follow these steps:
- remove the gravatar dependency from package.json,
- run npm update,
- add it back,
- run npm update again

**Comment by gopumon** [comment]
Old build system scrapped due to various bugs. Now `@infinitycube/gravatar@2.0.3` supports Angular 6 or later. Hope this resolve the issue.

**Comment by tvb** [comment]
Using 2.0.3 still failing with ng6:
>@infinitycube/gravatar: Appears to be a git repo or submodule.

**Comment by gopumon** [comment]
@tvb Unable to recreate the scenario here. Could you please provide the repo to examine the issue?

**Comment by tvb** [comment]
@gopumon from my AWS CodeBuild log output:
```
npm verb stack Error: /codebuild/output/src457301105/src/node_modules/@infinitycube/gravatar: Appears to be a git repo or submodule.
npm verb stack     at /usr/local/lib/node_modules/npm/node_modules/npm-install-checks/index.js:137:15
npm verb stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:287:18
npm verb stack     at FSReqWrap.oncomplete (fs.js:153:5)
npm verb cwd /codebuild/output/src457301105/src
npm verb Linux 4.14.33-51.34.amzn1.x86_64
npm verb argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--no-color" "--loglevel" "verbose"
npm verb node v8.11.0
npm verb npm  v5.6.0
npm ERR! path /codebuild/output/src457301105/src/node_modules/@infinitycube/gravatar
npm ERR! code EISGIT
npm ERR! git /codebuild/output/src457301105/src/node_modules/@infinitycube/gravatar: Appears to be a git repo or submodule.
npm ERR! git     /codebuild/output/src457301105/src/node_modules/@infinitycube/gravatar
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.
npm verb exit [ 1, true ]
```

**Comment by gopumon** [comment]
@tvb I believe you upgraded the package `@infinitycube/gravatar`

Two things you may try 

1. Completely remove the package and add it back

```
npm uninstall @infinitycube/gravatar  --save

npm install  @infinitycube/gravatar  --save
```
2. You run the following command from your project directory.

```
rm -rf node_modules/*/.git
```

**Comment by tvb** [comment]
I do indeed have 
```
cache:
  paths:
    - "node_modules/**/*"
```
for my CodeBuild project. Let me clean it and try again!

**Comment by tvb** [comment]
Jep that worked! Thanks!

**Comment by gopumon** [comment]
Glad to hear that. Happy Coding.
